### ISSUE TITLE
Splunk Cloud version

### ISSUE THREAD

**Issue by PKXLIVE** [supergnaw/phMDE-Security-Center#1]
Can you add an alternate version that would pull Windows Defender for endpoint strait to Splunk Cloud using REST API inputs?

**Comment by supergnaw** [comment]
> Can you add an alternate version that would pull Windows Defender for endpoint strait to Splunk Cloud using REST API inputs?

Interesting. I wasn't aware that on-prem vs cloud had such different operations. This isn't a fully completed version yet as I'm still working on it. What exact functionally are you looking for?

**Comment by supergnaw** [comment]
@PKXLIVE just following up

**Comment by supergnaw** [comment]
closing due to no response from issue opener.
